//LOADING
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

//ADMINISTRATIVE
export const GET_PROVINCES = "GET_PROVINCES";
export const GET_DISTRICTS = "GET_DISTRICTS";
export const GET_WARDS = "GET_WARDS";

//USER
export const GET_USER = "GET_USER";

//PROPERTIES
export const GET_PROPERTIES = "GET_PROPERTIES";
export const GET_MODIFYING_PROPERTY = "GET_MODIFYING_PROPERTY";

//CONTACT
export const GET_CONTACTS = "GET_CONTACTS";
export const GET_ALL_CONTACTS = "GET_ALL_CONTACTS";

//POST
export const GET_POSTS = "GET_POSTS";
export const GET_MODIFYING_POST = "GET_MODIFYING_POST";
