//ADMINISTRATIVE
export const GET_PROVINCES_SAGA = "GET_PROVINCES_SAGA";
export const GET_DISTRICTS_SAGA = "GET_DISTRICTS_SAGA";
export const GET_WARDS_SAGA = "GET_WARDS_SAGA";

//USER
export const POST_USER_LOGIN_SAGA = "POST_USER_LOGIN_SAGA";

//PROPERTIES
export const GET_PROPERTIES_SAGA = "GET_PROPERTIES_SAGA";
export const GET_PROPERTY_BY_SLUG_SAGA = "GET_PROPERTY_BY_SLUG_SAGA";
export const POST_PROPERTY_SAGA = "POST_PROPERTY_SAGA";
export const UPDATE_PROPERTY_SAGA = "UPDATE_PROPERTY_SAGA";
export const DELETE_PROPERTY_SAGA = "DELETE_PROPERTY_SAGA";

//CONTACT
export const GET_CONTACTS_SAGA = "GET_CONTACTS_SAGA";
export const UPDATE_CONTACT_SAGA = "UPDATE_CONTACT_SAGA";
export const DELETE_CONTACT_SAGA = "DELETE_CONTACT_SAGA";

//POST
export const GET_POSTS_SAGA = "GET_POSTS_SAGA";
export const GET_POST_BY_SLUG_SAGA = "GET_POST_BY_SLUG_SAGA";
export const POST_POST_SAGA = "POST_POST_SAGA";
export const UPDATE_POST_SAGA = "UPDATE_POST_SAGA";
export const DELETE_POST_SAGA = "DELETE_POST_SAGA";
